// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh4rrh8bSwIkhgdLKA4hsAhKggjzRJhkY',
    appId: '1:75387351147:android:f82c64892a40defcf4c12e',
    messagingSenderId: '75387351147',
    projectId: 'study-planner-b7c06',
    databaseURL: 'https://study-planner-b7c06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-planner-b7c06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkjY9K1lx3mLdReL_7x3bUhQM_ghkQww0',
    appId: '1:75387351147:ios:35eca7930944372ef4c12e',
    messagingSenderId: '75387351147',
    projectId: 'study-planner-b7c06',
    databaseURL: 'https://study-planner-b7c06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'study-planner-b7c06.firebasestorage.app',
    iosBundleId: 'com.example.flutterAuthTest',
  );
}
